### ISSUE TITLE
Enable Credit Card Payment/Gateway

### ISSUE THREAD

**Issue by malaoudi20** [maqalaqil/careplus#8]
Assigned to: @himyarjedri
Created At: 01/04/2020
Started At: 00/04/2020
Ended At: 00/04/2020
Deadline: 09/04/2020

- [ ] Enable payment gateway

**Comment by HimyarJedri** [comment]
if you need to add credit cards payments, look at this site and see prices : 
https://capitalepay.com/pricing/

there isn't any way to add it for free,

**Comment by malaoudi20** [comment]
Can we integrate Stripe or Paypal ? @himyarjedri
