### ISSUE TITLE
User Interface (check out)

### ISSUE THREAD

**Issue by malaoudi20** [maqalaqil/careplus#9]
Please remove unneccassry red dots from the user info box. See image below.

<img width="111" alt="Screen Shot 2020-04-04 at 1 06 38 PM" src="https://user-images.githubusercontent.com/34382301/78423121-4dfe8b00-7675-11ea-82be-b5e6e3862459.png">

<img width="436" alt="Screen Shot 2020-04-04 at 1 06 32 PM" src="https://user-images.githubusercontent.com/34382301/78423119-4ccd5e00-7675-11ea-9cdb-efbab472d8f9.png">

**Comment by HimyarJedri** [comment]
you mean from all ??

**Comment by malaoudi20** [comment]
Not everything....just anything below the asterisk (*) symbol.

**Comment by malaoudi20** [comment]
This should be removed if possible 
<img width="41" alt="Screen Shot 2020-04-06 at 2 44 32 PM" src="https://user-images.githubusercontent.com/34382301/78550442-26462900-7815-11ea-9f20-3e47b9d695ce.png">

**Comment by HimyarJedri** [comment]
Ok, got it.
